### PR TITLE
Browser: Switch to Google Chrome

### PR DESCRIPTION
**Pull request by Simonx22**
### Why?
We currently install Chromium from apt, which is version 73. This version was released on March 12, 2019. The current release is version 77. For security reasons it's good to have the latest version.

### What this PR does
This PR downloads the latest version from Google's servers and installs it. 
I also added `` "MetricsReportingEnabled": false`` to prevent a start up screen from happening. This disables error and crash reporting.

### Screenshot
image

### Remaining question
Can we use Google Chrome in an open source project?

### CODE REVIEW

**Comment by williamsthing** [comment]
I'll test this out locally soon, thanks for the contribution!

**Comment by JeDaYoshi** [comment]
You missed out that little one.

**Comment by Simonx22** [comment]
@JeDaYoshi thanks for fixing it!

**Comment by Simonx22** [comment]
This also fixes an issue with dark mode

### Chromium v73:

image


### Chrome v77:

image

**Comment by JeDaYoshi** [comment]
We're using now more recent versions of everything with 1421130 as we are using the stable version (as of the writing of this) of Debian, which leads to Chromium 76 - shouldn't be long until they push it to 77 anyway.

Is this okay? Given I'd still prefer to use Chromium version as it's open source. If the issue with dark mode disappears here it'd even be better.

**Comment by Simonx22** [comment]
Sure, that's fine! I think Chromium is definitely better for the open source version of Cryb. I will close this PR now.

**Comment by JeDaYoshi** [comment]
Just as a note, maybe this can be integrated in the future, just not as the default.

**Pull request closed without merging**
