### PR TITLE
Remove no-sandbox flag

### PR DESCRIPTION
**Pull request by plusreed**
As the portal runs under a limited user, we shouldn't need the no-sandbox flag.

### CODE REVIEW

**Comment by plusreed** [comment]
This needs to be tested if anyone is willing to do so for me. I don't have Docker on my Mac.

**Comment by plusreed** [comment]
f4a3224 should fix the issue where Chromium will not run without the flag.

**Comment by plusreed** [comment]
0c94737 enables user namespaces in Debian, since it's disabled by default. It turns out Chromium won't start unless this is enabled.

**Comment by plusreed** [comment]
Okay, so what's happening now is that we're having issues due to user namespaces not being enabled by default in Debian.

Our attempts to enable it have been pretty futile as the filesystem is R/O.

One thing I know to try is to try and switch the base image to something like Ubuntu Server, but I'm not sure about doing this. I believe Ubuntu has user namespaces in its kernel.

I'll install Docker and see if switching to Ubuntu Server will work.

**Comment by JeDaYoshi** [comment]
at this point I feel we're better keeping the no-sandbox

because enabling user namespaces like that would allow more issues and security problems, unless a different way is done

**Comment by AznManDown** [comment]
Per Reed's comment back in November, user namespaces are disabled and attempting to enable them are an issue. On top of that, JeDaYoshi's comment about potentially more security issues is valid. It has been decided to leave the --no-sandbox flag as is. Closing issue.

**Pull request closed without merging**
