### PR TITLE
Add audio support, change ffmpeg arguments for better performance, run everything as glados instead of root

### PR DESCRIPTION
**Pull request by JeDaYoshi**
* For audio this currently spawns two instances of ffmpeg, as Ly detailed in Cryb Discord server.
* ffmpeg should perform better with those new arguments.
* While also running as glados instead of root, increases security.

### CODE REVIEW

**Comment by williamsthing** [comment]
I think having a single ffmpeg command to do both video/audio would be ideal instead of having two ffmpeg processes which could effect overhead. Hopefully Ly in the Discord can get a PR for that soon

**Comment by JeDaYoshi** [comment]
I was waiting for Ly to commit changes, as I granted write permissions in my fork so we have it in the same PR.

**Comment by JeDaYoshi** [comment]
And yes, it can work in a single ffmpeg process, but it will affect the stream performance

**Comment by williamsthing** [comment]
Trying to start this locally but I'm getting the following crash

```
events.js:187
      throw er; // Unhandled 'error' event
      ^

Error: spawn pulseaudio ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:264:19)
    at onErrorNT (internal/child_process.js:456:16)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
Emitted 'error' event on ChildProcess instance at:
    at Process.ChildProcess._handle.onexit (internal/child_process.js:270:12)
    at onErrorNT (internal/child_process.js:456:16)
    at processTicksAndRejections (internal/process/task_queues.js:80:21) {
  errno: 'ENOENT',
  code: 'ENOENT',
  syscall: 'spawn pulseaudio',
  path: 'pulseaudio',
  spawnargs: [ '--exit-idle-time=-1', '--file=/bin/pulse-config.pa' ]
}
error Command failed with exit code 1.
```

I'll try and fix locally unless you have any suggestions!

**Comment by williamsthing** [comment]
Another issue:
```
[alsa @ 0x55c0e5a26e60] cannot open audio device default (No such file or directory)
default: Input/output error
```

This is from the ffmpeg process!

**Comment by JeDaYoshi** [comment]
@williamsthing It's fully implemented now and working - but before merging, I would like you to do some stuff first related to the ffmpeg args change, as I think this is happening when it shouldn't:

* Bitrate is higher than with past args
* More resources are used, and then performance degraded

Apparently by Ly these were going to perform well, but if you can confirm that's happening, I'd thank you if you did put back the past args to prevent issues with our users. Thanks!

**Comment by williamsthing** [comment]
I tried running this locally and there are *a lot* of performance issues, I think we should merge this with some flags to enable/disable this in `.env`, and keep this in beta until we can work on getting [the overhead down](https://github.com/crybapp/portal/issues/11) which would obviously help a lot. Good work tho!

**Comment by JeDaYoshi** [comment]
Have you tried if the old ffmpeg arguments perform better?

**Comment by williamsthing** [comment]
Will test this soon 👍

**Comment by JeDaYoshi** [comment]
After testing, I reached that my thoughts were wrong.

Probably VMs are failing more now due to a bit of more work given my pulseaudio (which cannot be removed) and the half of it by the new ffmpeg instance (cannot be removed either) - unless we magically get to make video recording use less CPU.

ffmpeg arguments changes have not much impact it seems, either way.

That said, I want to look as of why ffmpeg gives that lot of warnings.

My best bet for now is merge this - optionally add later an option to disable audio, while we look on giving ffmpeg better performance.

---

As a note: Audio choking is normal as video would also choke but would be less noticable. This part needs working in web, though.

**Comment by williamsthing** [comment]
I think we should add the option to enable/disable audio before we merge this just incase the user doesn't need to use audio (for whatever reason). I can try work on this if you want?

**Comment by JeDaYoshi** [comment]
Done!

**Comment by williamsthing** [comment]
Epical! Merging in now - thanks for the hard work @JeDaYoshi @lnneth 😄

**Pull request merged**
